# Two services: backend API on 5005, frontend (nginx) on 8000
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    env_file:
      - ./backend/.env        
    ports:
      - "5005:5005"

  frontend:
    build: 
      context: ./frontend
      args:
        VITE_API_URL=http://13.53.198.84:5005/api
    container_name: frontend
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - backend